### ISSUE TITLE
Compile error - no "send_out_image_array_online"

### ISSUE THREAD

**Issue by mooncupmc** [siatjiasen/Bart_in_Gadgetron#1]
Hello,

Thanks for sharing the code. 
I tried to compile the recent code, i found the following error. It seems no "send_out_image_array_online" function is defined. Would  you solve the issue? Thanks.

Building CXX object gadgets/bart/CMakeFiles/gadgetron_bart.dir/BartReconGadget.cpp.o
/home/moonc/mrprogs/gadgetron/gadgets/bart/BartReconGadget.cpp: In member function ‘virtual int Gadgetron::BartReconGadget::process(Gadgetron::GadgetContainerMessage<Gadgetron::IsmrmrdReconData>*)’: /home/moonc/mrprogs/gadgetron/gadgets/bart/BartReconGadget.cpp:229:8: error: ‘class Gadgetron::BartReconGadget’ has no member named ‘send_out_image_array_online’
  this->send_out_image_array_online(recon_bit_->rbit_[e], recon_obj_[e].recon_res_, e, image_series.

Chan

**Comment by siatjiasen** [comment]
Hi Chan,

Thank you for pointing out this error. Please check the new code.

The missing fuction 'send_out_image_array_online' was just a function in 'GenericReconGadget.cpp' created by me to modify the image header for online L1-ESPIRiT reconstruction. You could use the original function 'send_out_image_array' provided by Gadgetron.

I want to share the limitations of this BartReconGadget:
a. Only Cartesian 3D samplings were tested. 2D, 2DT, and 3DT sampling may need further modifiation of 'write_BART_array()' and 'read_BART_array()' in BartReconGadget.h for converting Gadgetron data to Bart data correctly.
b. You need to modify the path of bart in the 'L1_Espirit_Recon.sh', e.g. from '/home/amax/bart/bart' to 'Your_Path_of_Bart'. I suggest you to test the shell script without Gadgetron firstly. 
c.  Take care about the calibration mode of your data (integrated or separated). L1_ESPIRiT preferes integrated calibration due to a reasonable scaling factor is required for effective L1 regularization.
d.  BartGccGadget performs Geometric Coil Compression for Cartesian 3D data. You need to modify the path of Bart in the code in line 138, 143 and 148. 
e. If you run into crash, the folder storing data locates at the path where you run gadgetron.

f. This Gadget runs only on Linux due to Bart prefers Linux. 


If you encounter furhter problems, please let me know. 

Thank you. Best wishes, Jia Sen

**Comment by mooncupmc** [comment]
Thank you. I fixed it and compile works. Chan
